package vault

const (
	INTERNAL_SERVICES_STORE  = "internal-services"
	BUILD_RUNNER_SECRET_PATH = "BUILD_RUNNER"
	BR_ACCESS_ENCRYPTION_KEY = "ACCESS_ENCRYPTION_KEY"
	VPN_SERVER_PASSWORD_kEY  = "VPN_SERVER_PASSWORD"

	USER_DATA_STORE    = "user-data"
	SCM_TOKEN_PATH     = "scm-token-key"
	SCM_ENCRYPTION_KEY = "ENCRYPTION_KEY"
)
