package aws

const (
	AWS_ACCESS_KEY_ID       = "AWS_ACCESS_KEY_ID"
	AWS_SECRET_ACCESS_KEY   = "AWS_SECRET_ACCESS_KEY"
	AWS_ACCOUNT_ID_KEY      = "AWS_ACCOUNT_ID"
	AWS_REGION_KEY          = "AWS_REGION"
	VAULT_SECRET_PATH       = "S3"
	US_VAULT_SECRET_PATH    = "US-ACCOUNT"
	INDIA_VAULT_SECRET_PATH = "INDIA-ACCOUNT"
	AWS_CREDENTIALS_STORE   = "aws-credentials"
)
